version: "3.8"

services:
  bot-bannis:
    build:
      context: .
      target: development
    image: bot/bannis
    volumes:
      - ./src:/usr/app/bot-bannis/src
      - /usr/app/bot-bannis/node_modules
      - ./Logs:/usr/app/bot-bannis/Logs
    ports:
      - "5000:5000"
      - "9229:9229"
    env_file:
      - .env
    restart: on-failure
