version: "3.9"

services:
  bot-bannis:
    image: bot/bannis
    volumes:
      - ./src:/usr/app/bot-bannis/src
      - ./node_modules:/usr/app/bot-bannis/node_modules
      - ./Logs:/usr/app/bot-bannis/Logs
    ports:
      - "5000:5000"
      - "9229:9229"
    env_file:
      - .env
    restart: on-failure
